server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gcpdb?serverTimezone=Asia/Seoul
    username: playdata
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
